### ISSUE TITLE
Display answers to tasks (single task view)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#112]
![task-answers-table](https://user-images.githubusercontent.com/380007/75251325-0d446400-57e3-11ea-9575-8aa4030ee98c.png)

**Comment by tammets** [comment]
Display "Answers" tab for every role (logged in users).

**Comment by GlebRed** [comment]
Closed in https://github.com/centre-for-educational-technology/enrope_modules/commit/56aefd2d41297f773e55446e8c1afbda7d4d5f26
