### ISSUE TITLE
CAPTCHA registration error

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#114]
![Screenshot 2020-03-02 at 09 51 39](https://user-images.githubusercontent.com/380007/75655896-7e649b00-5c6b-11ea-9a42-d8e678d5220d.png)

**Comment by GlebRed** [comment]
Known issue https://www.drupal.org/project/recaptcha/issues/3035883 
Switched to math captcha

**Comment by GlebRed** [comment]
Still known issue. Applied patch  https://github.com/centre-for-educational-technology/enrope_modules/commit/3789f41cf99a50e2da16daaf45194a4f56188a7a
