### ISSUE TITLE
User registration form

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#12]
User are able to create new accounts by filling in following fields in the registration form:

- Username **(text field)**
- E-mail address **(text field)**
- First name **(text field)**
- Last name **(text field)**
- Profile picture **(upload image)**
- Affiliation **(text field)**
- Languages spoken **(pre-defined list, dropdown)**
- Research topic **(text field)**
- Research interests / fields **(text field, autocomplete)**
- Date of beginning research project **(date picker)**
- Expected end date of research project **(date picker)**
- Type of the research project (e.g. master thesis, dissertation etc) **(pre-defined list, dropdown)**
- Strengths (e.g. “I’ve got lots of experience with questionnaires in grammar schools and could help others with that”) **(text field)**
- recaptcha

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/enrope_modules@a8d73fb7c67fe889d3933c33940c7ca6364c64f9
