### ISSUE TITLE
Modification for text on landing page

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#24]
Change:
"ENROPE is an international, cooperative project aiming to provide high-quality qualification and networking structures for junior researchers in the field of language education and plurilingualism. The project was developed from within the LANGSCAPE network. ENROPE operates at the interface of language education..."

**Comment by GlebRed** [comment]
Closed in 8a7c73bc5bb94a03dacbbe006f0fba9beaaf0879
