### ISSUE TITLE
User registration form, add hint for selecting multiple items

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#25]
<img width="949" alt="screenshot 2019-01-29 at 13 19 06" src="https://user-images.githubusercontent.com/380007/51904912-8bf48500-23c8-11e9-8f95-06be9885fcee.png">

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/enrope_modules@74a304faf8e2ccfe3698364c7153b00f2b86dd30
