### ISSUE TITLE
Call for Application form, anonymous users

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#26]
Users are able to fill in the form without logging in. Remove file upload, replace it with text field (for adding URL to the file in Drive/Dropbox etc) and option (tick) e-mail the letter to info@enrope.eu

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/enrope_modules@74a304faf8e2ccfe3698364c7153b00f2b86dd30
