### ISSUE TITLE
User registration form - agree on terms

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/enrope_theme#30]
Add "I agree to terms and conditions and privacy policy" checkbox to user registration form. Phrases terms and conditions, privacy policy are linked to corresponding pages.

**Comment by tammets** [comment]
https://enrope.eu/terms-and-conditions
https://enrope.eu/privacy-policy

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/enrope_modules@1abdbaa043509d77679cf6ffd199e2f394a02efa
